name: RimWorld Deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  rimworld-deploy:
      uses: MemeGoddess/RimWorld-Deployment-Pipeline/.github/workflows/deploy.yml@beta
      secrets: inherit
      with:
          workshopId: '3526439840' 